msi_connectors:
  exit-addresses:
    duration_period: "rate(1 day)"
    client_type: "raw_text"
    source_type: "ip"
    tlp_level: "amber"
    labels: "tor-exit-node,anonymization-infrastructure"
    url: "https://check.torproject.org/exit-addresses"
    auth_type: "none"
    entity_types: "indicator,infrastructure,ipv4-addr"
    relationships: "based-on:indicator:ipv4-addr,consists-of:infrastructure:ipv4-addr"
    external_ref_name: "Tor Project"
    external_ref_url: "https://www.torproject.org/"
    external_ref_description: "The Tor Project official exit node list"
    ignore_regex: "^(ExitNode|Published|LastStatus).*"
    capture_zone: "ExitAddress\\s+([0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3})\\s+(\\d{4}-\\d{2}-\\d{2}\\s+\\d{2}:\\d{2}:\\d{2})"
    capture_regex: "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"
    capture_groups: "ip:1,timestamp:2"
  cta-cryptowall:
    duration_period: "rate(6 hours)" # Valid values: minute | minutes | hour | hours | day | days
    client_type: "raw_text"
    source_type: "ip"
    tlp_level: "green"
    labels: "malicious-activity,ransomware"
    url: "https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/cta_cryptowall.ipset"
    auth_type: "none"
    entity_types: "indicator,ipv4-addr"
    relationships: "based-on:indicator:ipv4-addr"
    external_ref_name: "FireHOL CryptoWall Ransomware IP BLocklist"
    external_ref_url: "https://github.com/firehol/blocklist-ipsets"
    external_ref_description: ""
    ignore_regex: "^#.*"
    capture_zone: "^([0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3})\\s*$"
    capture_regex: "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"
    capture_groups: "ip:1"
  cybercrime:
    duration_period: "cron(0 */3 ? * * *)"
    client_type: "html"
    source_type: "ip"
    # Not a TLP-AMBER source - Amber applied for testing
    tlp_level: "amber"
    labels: "malicious-activity,cybercrime"
    url: "http://cybercrime-tracker.net/fuckerz.php"
    auth_type: "none"
    entity_types: "indicator,ipv4-addr"
    relationships: "based-on:indicator:ipv4-addr"
    external_ref_name: "CyberCrime Tracker"
    external_ref_url: "http://cybercrime-tracker.net/"
    external_ref_description: "CyberCrime Tracker IP addresses from malicious activities"
    ignore_regex: ""
    capture_zone: "\\b([0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3})\\b"
    capture_regex: "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"
    capture_groups: "ip:1"
  cleantalk:
    duration_period: "cron(0 */3 ? * * *)"
    client_type: "html"
    source_type: "email"
    # Not a TLP-AMBER source - Amber applied for testing
    tlp_level: "amber"
    labels: "malware,botnet,command-and-control,ip-blocklist"
    url: "https://cleantalk.org/blacklists/top20"
    auth_type: "none"
    entity_types: "indicator,email-addr"
    relationships: "based-on:indicator:email-addr"
    external_ref_name: "Clean Talk Tracker"
    external_ref_url: "https://cleantalk.org/"
    external_ref_description: "Clean talk email addresses from phishing activities"
    ignore_regex: ""
    capture_zone: "([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,})"
    capture_regex: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"
    capture_groups: "email:1"
  ramblings:
    duration_period: "cron(0 */6 ? * * *)"
    client_type: "raw_text"
    source_type: "email"
    # Not a TLP-AMBER source - Amber applied for testing
    tlp_level: "amber"
    labels: "malware,botnet,command-and-control,phishing,spammers,ip-blocklist"
    url: "http://www.ram.org/ramblings/philosophy/spam/spammers.html"
    auth_type: "none"
    entity_types: "indicator,email-addr"
    relationships: "based-on:indicator:email-addr"
    external_ref_name: "Ramblings"
    external_ref_url: "http://www.ram.org/"
    external_ref_description: "Rambling email addresses from spammer activities"
    ignore_regex: ""
    capture_zone: "([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,})"
    capture_regex: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"
    capture_groups: "email:1"